# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'fr'
    app_locales: 'fr|en|de|it|es'
    app_path_translation : '%kernel.project_dir%/translations'
    app_path_config_cms : '%kernel.project_dir%/config/cms'
    app_path_menu_left_admin : '%app_path_config_cms%/admin/left-menu-admin.yaml'
    app_path_routes_modules : '%app_path_config_cms%/admin/translate_modules.yaml'
    app_path_global_options : '%app_path_config_cms%/admin/global_options.yaml'
    app_path_js : '%kernel.project_dir%/public/assets/js'
    app_path_js_admin : '%app_path_js%/admin'
    app_path_js_admin_asset : '/assets/js/admin/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
        bind:
            #$locales: '%app_locales%'
            #$defaultLocale: '%locale%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
