'admin_global_option#front': '__admin_global_option#front'
'admin_global_option#administration': '__admin_global_option#administration'
'admin_global_option#Titre du site': '__admin_global_option#Titre du site'
'admin_global_option#Site Web propulsé par Nathéo CMS': '__admin_global_option#Site Web propulsé par Nathéo CMS'
'admin_global_option#Rendre le front accessible aux visiteurs ?': '__admin_global_option#Rendre le front accessible aux visiteurs ?'
'admin_global_option#Si vous fermé le front, l''administration restera toujours accessible.': '__admin_global_option#Si vous fermé le front, l''administration restera toujours accessible.'
'admin_global_option#Changer le theme de l''administraton': '__admin_global_option#Changer le theme de l''administraton'
'admin_global_option#purple': '__admin_global_option#purple'
'admin_global_option#red': '__admin_global_option#red'
'admin_global_option#orange': '__admin_global_option#orange'
'admin_global_option#pink': '__admin_global_option#pink'
'admin_permission#Permission': '__ admin_permission#Permission'
'admin_system#System': '__admin_system#System'
'admin_role#Gestion des rôles': '__admin_role#Gestion des rôles'