'admin_global_option#front': '__admin_global_option#front'
'admin_global_option#administration': '__admin_global_option#administration'
'admin_global_option#Titre du site': '__admin_global_option#Titre du site'
'admin_global_option#Site Web propulsé par Nathéo CMS': '__admin_global_option#Site Web propulsé par Nathéo CMS'
'admin_global_option#Rendre le front accessible aux visiteurs ?': '__admin_global_option#Rendre le front accessible aux visiteurs ?'
'admin_global_option#Si vous fermez le front, l''administration restera toujours accessible.': '__admin_global_option#Si vous fermez le front, l''administration restera toujours accessible.'
'admin_global_option#Changer le theme de l''administration': 'admin_global_option#Changer le theme de l''administration'
'admin_global_option#Nombre d''éléments par page sur l''administration' : '__admin_global_option#Nombre d''éléments par page sur l''administration'
'admin_global_option#Langue par défaut de l''administration' : '__admin_global_option#Langue par défaut de l''administration'
'admin_global_option#Format de la date et de l''heure' : '__admin_global_option#Format de la date et de l''heure'
'admin_global_option#Violet': '__admin_global_option#Violet'
'admin_global_option#Rouge': '__admin_global_option#Rouge'
'admin_global_option#Orange': '__admin_global_option#Orange'
'admin_global_option#Rose': '__admin_global_option#Rose'
'admin_global_option#Format de l''heure' : '__admin_global_option#Format de l''heure'
'admin_global_option#Ce format est utilisé pour afficher l''heure sur le site (front et admin).' : '__admin_global_option#Ce format est utilisé pour afficher l''heure sur le site (front et admin).'
'admin_global_option#Format de la date raccourcie' : '__admin_global_option#Format de la date raccourcie'
'admin_global_option#Ce format est utilisé pour afficher la date dans les tableaux.' : '__admin_global_option#Ce format est utilisé pour afficher la date dans les tableaux.'
'admin_global_option#Format de la date' : '__admin_global_option#Format de la date'
'admin_global_option#Ce format est utilisé pour afficher la date sur le site (front et admin).' : '__admin_global_option#Ce format est utilisé pour afficher la date sur le site (front et admin).'
'admin_permission#Permission': '__ admin_permission#Permission'
'admin_system#System': '__admin_system#GlobalFunction'
'admin_role#Gestion des rôles': '__admin_role#Gestion des rôles'
'front_front#Site public' : '__front_front#Site public'
'admin_system#Systeme' : '__admin_system#Systeme'
'admin_pagination#Pagination' : '__admin_pagination#Pagination'
'admin_topmenu#Menu Top' : '__admin_topmenu#Menu Top'
'admin_translation#fr': '__admin_translation#fr'
'admin_translation#en': '__admin_translation#en'
'admin_translation#de': '__admin_translation#de'
'admin_translation#it': '__admin_translation#it'
'admin_translation#es': '__admin_translation#es'
'admin_system#Administration' : '__admin_system#Administration'
'admin_auth#Authentification' : '__admin_auth#Authentification'
'admin_global_option#Options pour le front' : '__admin_global_option#Options pour le front'
'admin_global_option#Options sur l''administration' : '__admin_global_option#Options sur l''administration'
'admin_global_option#Script dans la balise HEAD' : '__admin_global_option#Script dans la balise HEAD'
'admin_global_option#Ajouter vos scripts qui doivent être exécutés dans la balise HEAD.' : '__admin_global_option#Ajouter vos scripts qui doivent être exécutés dans la balise HEAD.'
'admin_global_option#Script juste après l''ouverture de la balise BODY' : '__admin_global_option#Script juste après l''ouverture de la balise BODY'
'admin_global_option#Ajouter vos scripts qui doivent être exécutés à l''ouverture de la balise BODY.' : '__admin_global_option#Ajouter vos scripts qui doivent être exécutés à l''ouverture de la balise BODY.'
'admin_global_option#Script juste avant la fermeture de la balise BODY' : '__admin_global_option#Script juste avant la fermeture de la balise BODY'
'admin_global_option#Ajouter vos scripts qui doivent être exécutés à la fermeture de la balise BODY.' : '__admin_global_option#Ajouter vos scripts qui doivent être exécutés à la fermeture de la balise BODY.'

