# MENU DE GAUCHE DE l'ADMINISTRATION
# Assurez-vous que les targets (routes) soit exact avant de les changer sinon risque de casser le site

menu-left-admin:
  admin_dashboard#Dashboard:
    icon: 'fa-tachometer-alt'
    target: 'admin_dashboard_index'
  admin_permission#Permission:
    icon: 'fa-dice-d6'
    sub-menu:
      admin_role#Gestion des rôles:
        icon: 'fa-user-tag'
        target: 'admin_role_index'
  admin_system#System:
    icon: 'fa-cogs'
    sub-menu:
      admin_route#Gestion des routes:
        icon: 'fa-road'
        target: 'admin_route_index'
      admin_translation#Gestion des traductions:
        icon: 'fa-language'
        target: 'admin_translation_index'
      admin_global_option#Options globales:
        icon: 'fa-cog'
        target : 'admin_option_index'
      admin_system#Debug System:
        icon: 'fa-bug'
        target: 'admin_system_index'