# Traductions des modules des routes
routes_modules:
  dashboard : 'admin_dashboard#Dashboard'
  route: 'admin_route#Gestion des routes'
  front: 'front_front#Site public'
  security: 'front_auth#Authentification'
  option : 'admin_global_option#Options globales'
  translation: 'admin_translation#Gestion des traductions'
  global_option: 'admin_global_option#Options globales'
  system : 'front_auth#Authentification'