# Traductions des modules des routes
routes_modules:
  dashboard : 'admin_dashboard#Dashboard'
  route: 'admin_route#Gestion des routes'
  front: 'front_front#Site public'
  security: 'front_auth#Authentification'
  option : 'admin_global_option#Options globales'
  translation: 'admin_translation#Gestion des traductions'
  global_option: 'admin_global_option#Options globales'
  system : 'admin_system#System'
  pagination : 'admin_pagination#Pagination'
  role : 'admin_role#Gestion des rôles'
  admin: 'admin_system#Administration'
  auth: 'admin_auth#Authentification'
  permission : 'admin_permission#Permission'
  topmenu : 'admin_topmenu#Menu Top'
  fixture : 'admin_fixture#Jeu de données'